language: scala

scala:
   - 2.11.8
   - 2.10.6
jdk: oraclejdk8

script:
   - sbt ++$TRAVIS_SCALA_VERSION "scalaJsonASTJVM/testOnly specs.*"
   - sbt ++$TRAVIS_SCALA_VERSION "scalaJsonASTJS/testOnly specs.*"
